### ISSUE TITLE
Cannot fetch Members' GUID when using `listMembers`

### ISSUE THREAD

**Issue by vamsee-gomatam** [mxenabled/atrium-php#10]
Hello,

I am trying to use the `listMembers` function to fetch all the members associated with a user account. While the Postman collection shows a `guid` (string) attribute for each member in the API response, the PHP model's `getGuid` function returns a `bool` (which is actually as per documentation).

However, this means there is no way for me to fetch all the Members data programatically and save a Member GUID for any later operations.

I have also noticed that changing the data (cast) type of `guid` from `bool` to `string` [https://github.com/mxenabled/atrium-php/blob/master/lib/model/Member.php#L49] works as expected i.e., `$member->getGuid()` returns the actual GUID string.

Is there any reason why the default return for `getGuid` is boolean? Is there any other way for me to programatically fetch all Members' GUIDs for a given User GUID?

Any help would be much appreciated.

**Comment by brettmortensen** [comment]
@vamsee-gomatam Thank you for reaching out about this issue.

It appears a typo snuck in during the update to our latest major version. As you pointed out, this field should be a string instead of a boolean.

This has been updated here: https://github.com/mxenabled/atrium-php/commit/dc00730ae33353290ce253092ce84d57eb571605
